---
- hosts: localhost
  become: true

  tasks:
  - name: Update apt-cache
    apt: update_cache=yes

  - name: Install Packages
    apt: name={{ item }} state=latest
    with_items: [ 'git', 'gitk', 'curl', 'vlc', 'aptitude', 'postgresql', 'calibre', 'ruby', 'npm']

  - name: Add git aliases
    command: git config --global alias.co checkout
  - name: Add git aliases
    command: git config --global alias.br branch
  - name: Add git aliases
    command: git config --global alias.ci commit
  - name: Add git aliases
    command: git config --global alias.st status
  - name: Add git aliases
    command: git config --global alias.aa "add ."

  - name: Install elm" node.js package.
    npm:
      name: elm
      global: yes


  roles:
  - { role: gantsign.atom, become: yes  }
  - { role: mjanser.powerline, become: yes, powerline_users: lorenzo }
  - { role: rvm_io.ruby,
      become: yes,
      tags: ruby,
      rvm1_rubies: ['ruby-2.5.0'],
      rvm1_user: 'lorenzo'
    }
  - { role: mhalano.skypeforlinux, become: yes  }
  - { role: tersmitten.megacli, become: yes }
  - { role: azmodude.googlechrome, become: yes  }
