---
- hosts: localhost
  become: true

  tasks:
  - name: Update apt-cache
    apt: update_cache=yes
  - name: Install Packages
    apt: name={{ item }} state=latest
    with_items: [ 'git', 'curl', 'vlc', 'aptitude', 'postgresql', 'calibre' ]

  roles:
  - { role: gantsign.atom, become: yes  }
  - { role: mjanser.powerline, become: yes, powerline_users: lorenzo }
  - { role: rvm_io.ruby, 
      become: yes,
      tags: ruby,
      rvm1_rubies: ['ruby-2.5.0'],
      rvm1_user: 'lorenzo'  
    }
  - { role: mhalano.skypeforlinux, become: yes  }
  - { role: tersmitten.megacli, become: yes }
  - { role: azmodude.googlechrome, become: yes  }
