# Install atom
- src: gantsign.atom

# Install powerine
- src: mjanser.powerline

# Install rvm
- src: aeriscloud.rvm

# Install skype
- src: mhalano.skypeforlinux

# Install chrome
- src: azmodude.googlechrome

# Install docker
- src: geerlingguy.docker

# Install Tilix terminal
- src: KeyboardInterrupt.tilix
