# Install atom
- src: gantsign.atom

# Install powerine
- src: mjanser.powerline

# Install rvm
- src: rvm_io.ruby

# Install skype
- src: mhalano.skypeforlinux

# Install mega
- src: tersmitten.megacli

# Install chrome
- src: azmodude.googlechrome

# Install docker
- src: nickjj.docker

# Install Tilix terminal
- src: KeyboardInterrupt.tilix
