# Install atom
- src: gantsign.atom

# Install powerine
- src: mjanser.powerline

# Install rvm
- src: altermn.rvm

# Install skype 
- src: mhalano.skypeforlinux

# Install mega
- src: kostyrevaa.megacli
